name: CI checks on PR

on: pull_request

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 
        yarn install --frozen-lockfile && yarn lint
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install && sudo yarn global add @lhci/cli@0.7.x
      - run: yarn build:staging
      - run: lhci autorun